### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by hugochmt** [PolytechLyon/isi3-tp1-graph-chomarat-borghino#1]
Bonjour, serait-il possible d'avoir un retour sur notre travail ?
Merci.

**Comment by Vipeross** [comment]
Nous avons modifié notre TP et rédigé notre compte rendu, pourrions nous avoir à nouveau votre avis ?
Merci.

**Comment by Slashgear** [comment]
C'est déjà bien mieux 👍 

Sur l'iterator j'aurai maintenant qu'un seul retour

- [ ] Il existe des types de List en Java qui permettent de représenter des Queues et des Files. Je ne vous demande pas de changer votre implémentation mais pouvez vous m'indiqué les types qui seraient plus appropriés ?

**Comment by hugochmt** [comment]
Merci pour votre retour. Concernant l'algorithme de parcours en profondeur une `Stack` serait plus appropriée pour récupérer le dernier élément avec la méthode `pop()`. Pour le parcours en largeur, il semblerait que l'utilisation d'une `LinkedList` soit plus convenable pour récupérer le premier élément de la file avec la méthode `poll()`.
